import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
// import { GeistMono } from 'geist/font/mono';

import './globals.css';
import NavBar from '@/components/nav';
import Footer from '@/components/footer';
import { ThemeProvider } from '@/components/theme-provider';
import { TailwindIndicator } from '@/components/tailwind-indicator';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={GeistSans.className}>
      <body>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <main className='flex min-h-screen flex-col items-center justify-between'>
            {children}
          </main>
          <TailwindIndicator />
        </ThemeProvider>
        <NavBar />

        <Footer />
      </body>
    </html>
  );
}
